version: "3.8"

services:
  fornecedor-db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fornecedor-db
      - MYSQL_USER=fornecedor
      - MYSQL_PASSWORD=fornecedor
    volumes:
      - "fornecedor-db-data:/var/lib/mysql"
    networks:
      - "spring-cloud-network"
    ports:
      - "3306:3306"

volumes:
  fornecedor-db-data:
    driver: local

networks:
  spring-cloud-network:
    driver: bridge
