
server:
  port: 8888
  
spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - /Users/aleoliv/developer/projects/workspaces/sts4/spring-cloud/cloud-repo